# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no

# 设置字体为霞鹜文楷等宽字体 (LXGW WenKai Mono)
# 字体文件已放在 portable_config/fonts/ 目录下
#osd-font= Microsoft YaHei
osd-font=LXGW WenKai Mono

# log-file=mpv.log
msg-level=all=info,epg=trace
msg-level=ffmpeg=no

 ## AMD核显最优解码
gpu-context=d3d11
hwdec=auto
hwdec-codecs=all
temporal-dither=yes

# --- 渲染优化 ---
# profile=high-quality           # 使用高质量预设,集成显卡不要使用
vo=gpu-next                   # 使用新的GPU渲染器，提供更好的性能和质量

# # 缓存 #
cache=yes
# 强制内存储存，不要写入硬盘，保护固态硬盘寿命
cache-on-disk=no
# 告诉 mpv 只要有可能，尽量往后预读多少秒的数据（作为期望值）
# cache-secs=1048
#向前缓存最大值
demuxer-max-bytes = 1024MiB
# 向后缓存最大值 (保留已播放过的内容，确保往前拖动进度条时不卡顿)
demuxer-max-back-bytes=1048MiB

## 窗口秒开
force-window=immediate
idle=yes

## 固定1080P窗口和位置
autofit=1920x1080
geometry=1920x1080+1920-1040
keepaspect=yes
# ontop=yes

# --- 音频倍速 ---
audio-pitch-correction=yes
# 加上特定的参数，强制 rubberband 专注处理音高
af=rubberband

# 预加载回看续播,续播减少卡顿
prefetch-playlist=yes

#IPTV配置
# 或者伪装成常见的智能电视/机顶盒 
user-agent=SYTV/1.6
# 2. 忽略 SSL ,很多个 IPTV 源 HTTPS 证书是无效的
tls-verify=no
# # 4. 底层断线自动重连 (对抗不稳定源的神器)
# # 传递给底层的 ffmpeg (libavformat)，让它在网络断开或超时时自动重试
# demuxer-lavf-o=reconnect=1,reconnect_at_eof=1,reconnect_streamed=1,reconnect_delay_max=5
# # 5. 超时与网络相关
# network-timeout=10          # 连接超时时间（秒）
# stream-buffer-size=4m       # 加大流缓冲区

# # --- 画质轻度优化 (核显高性价比方案) ---
# # --- 渲染与补帧 ---
# interpolation=yes
# tscale=oversample
# video-sync=display-resample
# blend-subtitles=yes
# # 默认值偏大，我们把它改小，让它在 IPTV 时间戳混乱时直接放弃重采样音频，而不是制造电音
# video-sync-max-audio-change=0.01

# # 1. 去色带 (对抗低码率画质劣化),开启 deband 可以让色彩过渡变得顺滑。
# deband=yes
# deband-iterations=2    # 算法迭代次数，2 是画质和性能的完美平衡
# deband-threshold=35    # 阈值，稍微调高点以应对 IPTV 的高压缩率
# deband-range=16        # 作用范围
# deband-grain=4         # 增加一点点动态噪点，掩盖粗糙的色块

# # 2. 更换更优质的缩放算法
# # scale=ewa_lanczos      # 使用更高级的 Jinc 算法，画面更锐利、细节更好
# # scale-antiring=0.7     # 必须配合上一行使用！用于消除高级锐化算法带来的“高亮白边（振铃效应）”
# sigmoid-upscaling=yes  # 减少拉伸时产生的亮部/暗部边缘锯齿（振铃效应）
# sharpen=0.5

# ==========================================
# --- 直播抗抖动 (强制初始缓冲) ---
# ==========================================

# 强制 mpv 在刚打开视频（或切台）时，先憋住不播，强制进入“缓冲中”的状态
cache-pause-initial=yes

# 设定解除缓冲状态的阈值：当内存里攒够多少秒的数据时，才正式开始播放避免,避免无线网络波动卡一下
# 建议设为 2 到 3 秒。你可以先设为 2 测试一下。
cache-pause-wait=0

