# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no

# 设置字体为霞鹜文楷等宽字体 (LXGW WenKai Mono)
# 字体文件已放在 portable_config/fonts/ 目录下
# 也可以尝试以下备选字体名，如果上面的不工作：
# osd-font=LXGWWenKaiMono
# osd-font=LXGW WenKai Mono Regular
#osd-font= Microsoft YaHei

osd-font=LXGW WenKai Mono


log-file=mpv.log
msg-level=all=info,epg=trace

scale=ewa_lanczossharp
cscale=ewa_lanczossharp

 ########
 # 基础 #
 ########

 vo = gpu-next
#gpu-context = winvk
#d3d11-exclusive-fs = yes
#d3d11-flip = no

 hwdec = auto-copy
 hwdec-codecs = h264,hevc,vp8,vp9,av1,ffv1


 msg-level=ffmpeg=no